 repos:
  - repo: local
    hooks:
      - id: black
        name: black-test
        entry: black --check -l 200 -t py311 .
        always_run: true
        pass_filenames: false
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python manage.py test apps --keepdb
        always_run: true
        pass_filenames: false
        language: system
        types: [python]
