version: '3'
services:
  mariadb:
    image: mariadb:10
    container_name: "mariadb"
    ports:
      - 3306:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
      - "./mariadb/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_DATABASE: service_db
      MARIADB_USER: db_user
      MARIADB_PASSWORD: db_user1!
      MARIADB_ROOT_PASSWORD: root1!
    restart: always

volumes:
  static_volume:
